// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi2NB11yo4KGh9nAHP_sVb7ydKFtWmS4Q',
    appId: '1:945517996640:web:078eca8ded329db86af105',
    messagingSenderId: '945517996640',
    projectId: 'beauty-habit-tracker',
    authDomain: 'beauty-habit-tracker.firebaseapp.com',
    databaseURL: 'https://beauty-habit-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'beauty-habit-tracker.appspot.com',
    measurementId: 'G-776BEB101J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmroi30AN1D4b3ZTZDvD0lalWaqOCNunI',
    appId: '1:945517996640:android:6a8416d1974d81036af105',
    messagingSenderId: '945517996640',
    projectId: 'beauty-habit-tracker',
    databaseURL: 'https://beauty-habit-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'beauty-habit-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGeT_1M3M9JQj8IQV9A-UM2qEEM9uBO-w',
    appId: '1:945517996640:ios:b4a0f6684c17bace6af105',
    messagingSenderId: '945517996640',
    projectId: 'beauty-habit-tracker',
    databaseURL: 'https://beauty-habit-tracker-default-rtdb.firebaseio.com',
    storageBucket: 'beauty-habit-tracker.appspot.com',
    iosClientId:
        '945517996640-m3osdkq8o6r129ovr898b01eog4kfp6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.beautyHabitTracker',
  );
}
