import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:intl/intl.dart';

final brandList = [
  'Acqua di Parma',
  'Aesop',
  'Aveda',
  'Bobbi Brown',
  'BON PARFUMEUR',
  'Bioderma',
  'Boscia',
  'Burberry',
  'BUTTAH SKIN',
  'Buxom',
  'By Rosie Jane',
  'By Terry',
  'BYREDO',
  'CHANEL',
  'Chantecaille',
  'Charlotte Tilbury',
  'Christian Louboutin',
  'Ciaté',
  'Clarins',
  'Clinique',
  'Clé de Peau Beauté',
  'COLORESCIENCE®',
  'CTZN COSMETICS',
  'DIOR',
  'Dr. Jart+',
  'EltaMD',
  'Elemis',
  'ELIXIR',
  'EMILIE HEATHE',
  'EPARA',
  'Erbaviva',
  'Erno Laszlo',
  'Estée Lauder',
  'EVE LOM',
  'Elizabeth Arden',
  'FELLOW BARBER',
  'FIELDTRIP',
  'Filorga',
  'First Aid Beauty',
  'FLORAL STREET',
  'FOREO',
  'Fresh®',
  'Givenchy',
  'GLAMGLOW®',
  'Gucci',
  'Guerlain',
  'HOURGLASS',
  'IT COSMETICS',
  'IPSA',
  'Jimmy Choo',
  'Jo Malone London™',
  'Joaquina Botánica',
  'Kate Somerville®',
  'Kiehl\'s Since 1851',
  'Kylie Skin',
  'L\'Occitane'
      'La Mer',
  'La Perla',
  'La Prairie',
  'Laura Mercier',
  'Lancôme',
  'MAC Cosmetics',
  'Murad®',
  'NARS',
  'Neutrogena',
  'Odacité',
  'Omorovicza',
  'Oribe',
  'Origins',
  'Perricone MD',
  'philosophy',
  'RéVive®',
  'Sulwhasoo',
  'SHISEIDO',
  'Tom Ford',
  'The Ordinary',
  'THE GINZA',
  'Tatcha',
  'Too faced',
  'Versace',
  'Yves Saint Laurent',
];

final typeList = [
  'Cleansers',
  'Exfoliators & Peels',
  'Eye Creams & Treatments',
  'Facial Masks',
  'Face Mists & Essences',
  'Face Moisturizers',
  'Face Oils',
  'Gifts & Sets',
  'Lip Balms & Treatments',
  'Makeup Remover',
  'Serums & Treatments',
  'Sunscreen & Self-Tanners',
  'Toners',
  'Hair & Scalp Treatments',
  'Shampoo',
  'Conditioner',
  'Dry Shampoo',
  'Body Moisturizers',
  'Body Wash & Shower Gel',
  'Blush',
  'Bronzer',
  'Brushes & Tools',
  'Concealer',
  'Contouring',
  'Eyebrows',
  'Eyelashes',
  'Eyeliner',
  'Eyeshadow',
  'Foundation',
  'Highlighter',
  'Lipstick, Lip Gloss & Liner',
  'Mascara',
  'Nail Polish & Care',
  'Palettes',
  'Powder & Setting Spray',
  'Primer',
];
final statusList = ['Sealed', 'Opened'];
final paoList = [36, 30, 24, 18, 15, 12, 9, 6, 3];
final defaultMaxTime = Timestamp.fromDate(DateTime(3000, 1, 1));
const defualtImageLink =
    'https://firebasestorage.googleapis.com/v0/b/beauty-habit-tracker.appspot.com/o/defualt_setting%2FiTunesArtwork%402x.png?alt=media&token=6045da08-2d82-45f7-b836-ab46aaf6b078';

displayTime(Timestamp? time) {
  if (time == null || time == defaultMaxTime) {
    return '----/--/--';
  } else {
    return DateFormat('yyyy-MM-dd').format(time.toDate());
  }
}
